# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencmis', '0015_auto_20161008_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baselineassessment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='baselineassessment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='baselinevalue',
            name='date',
        ),
        migrations.RemoveField(
            model_name='baselinevalue',
            name='place',
        ),
        migrations.RemoveField(
            model_name='baselinevalue',
            name='user',
        ),
        migrations.DeleteModel(
            name='BaselineAssessment',
        ),
    ]
